# Nome da aplicação e porta.
spring.application.name=api-diario
server.port=8081
server.address=0.0.0.0

# Configurações de conexão com o banco em memória H2.
spring.datasource.url=jdbc:h2:mem:diariodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=dba
spring.datasource.password=12345

# Dialeto do Hibernate para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria e atualiza as tabelas automaticamente com base nas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL no console do IntelliJ
spring.jpa.show-sql=true

# Habilita a interface web do H2 para vermos os dados.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
